### PR TITLE
extend OS_MGMT_RET_RC

### PR DESCRIPTION
**Pull request by tomaszduda23**
extend OS_MGMT_RET_RC base on https://docs.zephyrproject.org/latest/services/device_mgmt/mcumgr.html#c.mcumgr_err_t

### CODE REVIEW

**Comment by JPHutchins** [comment]
Thanks, looking into this now!

**Comment by tomaszduda23** [comment]
It seems that both are mixed even in the same function https://github.com/nrfconnect/sdk-zephyr/blob/e9bb83320a4cd303135203fae18136a71e87f26e/subsys/mgmt/mcumgr/grp/os_mgmt/src/os_mgmt.c#L480C1-L483C47. MGMT_ERR_ENOTSUP is definitely possible. https://github.com/NordicSemiconductor/Android-nRF-Connect-Device-Manager does some mapping depending on group. I'm not sure if the mapping can be perfect though.

Maybe it would be better to allow int values for unknown values. I added this to not catch exception here https://github.com/tomaszduda23/smpclient/blob/d25c8035ae2858fd41a106058297b619d58fbcb5/smpclient/__init__.py#L62

**Comment by JPHutchins** [comment]
IMO you've found a mistake, or possibly legacy support for past mistakes, in Zephyr's SMP server implementation!

If you have time, take a look at the SMP spec here, https://docs.zephyrproject.org/latest/services/device_mgmt/smp_protocol.html, and see if that sheds any light on this.

BTW, no one seems to use the flag bits that are available in the header.  It would be possible to use the flag bits to specify the namespace of the return code.  Of course the spec would need to be revised.

**Comment by JPHutchins** [comment]
@tomaszduda23 I think that I see!

image

I made the mistake of implementing SMP Version 2 instead of SMP Version 1.

This PR should be updated to use the OS_MGMT RCs from here: https://docs.zephyrproject.org/latest/services/device_mgmt/mcumgr.html#c.mcumgr_err_t

Separately, this SMP library needs to understand that the error response is a union of SMP Version 1 and Version 2 errors.  The `mcumgr_err_t` enums would be defined as the type of an SMP Version 1 return, which is what Zephyr implements (mostly, I think... 🤣 )

LMK what you think!

**Comment by tomaszduda23** [comment]
I was just about to point out the same thing.

**Comment by JPHutchins** [comment]
Another note is that smpclient, at the application layer, wants to discard this nonsense: https://github.com/intercreate/smpclient/blob/4942251bf4256643fd8878641aa08519a6693d9b/smpclient/generics.py#L17-L28

**Review by JPHutchins — APPROVED** [review]

**Pull request merged**
